#!/bin/sh
# Copyright (C) 2003, 2010, 2011 Thien-Thi Nguyen
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301  USA
##
# usage: cov
# env vars required: srcdir

test -n "${srcdir}"

sed -f "${srcdir}/../build-aux/tsar-names.sed" \
    ../*/*.tsar \
    | sort \
    > TMP-dot-tsar-files

sed -e '/@tsin i /!d' \
    -e 's///' \
    ${srcdir}/*.texh \
    | sort \
    > TMP-tsin-i-directives

diff -u TMP-dot-tsar-files TMP-tsin-i-directives > TMP

if [ -s TMP ] ; then
    echo 'ERROR: bad doc coverage!'
    cat TMP
    rm TMP-* TMP
    exit 1
fi

rm TMP-* TMP
exit 0

# cov ends here
